<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Keluar</name>
   <tag></tag>
   <elementGuidId>a8b09307-76cb-4a0c-b11e-1ea1d69a4f49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/section/div/div[2]/ul/li[6]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Keluar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>39f2db23-1fcd-41a0-86c0-0bc65f717507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full text-error-3 hover:bg-rose-300 border-b border-black hover:border-transparent flex font-medium font-poppins text-lg lg:text-xl gap-4 rounded-md py-4 px-2.5</value>
      <webElementGuid>7ad5430a-49d2-4be0-b583-b4a52ca7f3db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keluar</value>
      <webElementGuid>fa1b6871-ab0a-4f8f-abdf-e7f4a7b3be66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/section[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;fixed z-50 w-72 bg-main-color h-full hidden lg:block&quot;]/div[@class=&quot;px-4 lg:mt-4&quot;]/ul[@class=&quot;flex flex-col gap-2.5&quot;]/li[6]/button[@class=&quot;w-full text-error-3 hover:bg-rose-300 border-b border-black hover:border-transparent flex font-medium font-poppins text-lg lg:text-xl gap-4 rounded-md py-4 px-2.5&quot;]</value>
      <webElementGuid>b5f97de3-25da-47f8-ac9f-03cd10b4d895</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/section/div/div[2]/ul/li[6]/button</value>
      <webElementGuid>9c3ab52a-bd1a-4a00-b46a-ce16a9507908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berita'])[1]/following::button[1]</value>
      <webElementGuid>0aee3ee7-46bb-41e0-99ae-3e4571bdc541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/following::button[1]</value>
      <webElementGuid>7197d03f-8599-4b32-b8e3-88ce37c21908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan Diterima'])[1]/preceding::button[1]</value>
      <webElementGuid>56f4935e-f20b-4a84-b2d5-e820e6f7050c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terverifikasi'])[1]/preceding::button[1]</value>
      <webElementGuid>8ee8548b-7155-4742-9f49-96fc4f389955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Keluar']/parent::*</value>
      <webElementGuid>399b25db-132c-4a76-a942-e88e93e88287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/button</value>
      <webElementGuid>5b256a5f-8105-4466-93f0-fccfa5a999a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Keluar' or . = 'Keluar')]</value>
      <webElementGuid>c7e0b2f9-9a8f-4291-b260-40f21b05525e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
