<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Complaint</name>
   <tag></tag>
   <elementGuidId>35d8f867-aab2-442c-a9c1-44399bd7d3af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/section/div/div[2]/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Complaint&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>00a604b0-54ab-48f5-a147-0a57ae0d6771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-b hover:bg-white border-black hover:border-transparent flex font-medium font-poppins text-lg lg:text-xl gap-4 rounded-md py-4 px-2.5 </value>
      <webElementGuid>221ddf13-f2ab-433c-8a2e-ba237bb157c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/complaint</value>
      <webElementGuid>f8426a05-d566-4ec4-b3b1-332016e26563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Complaint</value>
      <webElementGuid>8c6b9880-c078-4a01-802e-15d185518116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/section[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;fixed z-50 w-72 bg-main-color h-full hidden lg:block&quot;]/div[@class=&quot;px-4 lg:mt-4&quot;]/ul[@class=&quot;flex flex-col gap-2.5&quot;]/li[2]/a[@class=&quot;border-b hover:bg-white border-black hover:border-transparent flex font-medium font-poppins text-lg lg:text-xl gap-4 rounded-md py-4 px-2.5&quot;]</value>
      <webElementGuid>4d41d511-04fe-4b02-9ea4-eeac75b190e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/section/div/div[2]/ul/li[2]/a</value>
      <webElementGuid>03ddd8e1-dde6-40cc-a78b-c845dd474118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Complaint')]</value>
      <webElementGuid>a563c7f1-33fe-447e-913a-014e8da2bd92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/following::a[1]</value>
      <webElementGuid>92faad67-6218-4000-bf48-7be715dc7143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::a[2]</value>
      <webElementGuid>548f86ee-e7c4-4203-8e43-9d783ee62b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chat Page'])[1]/preceding::a[1]</value>
      <webElementGuid>ceef61fa-01cc-4f3b-8607-1fc4310e045f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/preceding::a[2]</value>
      <webElementGuid>5dd1885c-998b-4514-8992-4a9050c705f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Complaint']/parent::*</value>
      <webElementGuid>b3668cec-b788-4fcf-a388-1e5d6a579303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/complaint')]</value>
      <webElementGuid>01bd6567-6f1f-4f4f-9ac3-1b137df68d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>855a2188-1bc1-4d9d-94ed-dc1c7961aadd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/complaint' and (text() = 'Complaint' or . = 'Complaint')]</value>
      <webElementGuid>862a083e-f31f-4c76-add8-9f329ac283a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
