<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Berita</name>
   <tag></tag>
   <elementGuidId>11d93159-f20f-4d7c-a90d-0bec7c31537a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/section/div/div[2]/ul/li[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Berita&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9e67c3df-125b-445e-9657-f844f4f1bbaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-b hover:bg-white border-black hover:border-transparent border-b hover:bg-white border-black hover:border-transparent border-b hover:bg-white border-black hover:border-transparent border-b hover:bg-white border-black hover:border-transparent flex font-medium font-poppins text-lg lg:text-xl gap-4 rounded-md py-4 px-2.5 </value>
      <webElementGuid>5281f662-8440-43f4-825c-ba4b7415a528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/news</value>
      <webElementGuid>e17ab0a0-1d37-45ac-aa4c-4cdaf0b17e25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Berita</value>
      <webElementGuid>5708bac7-65bf-4b7c-b543-2106922f2215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/section[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;fixed z-50 w-72 bg-main-color h-full hidden lg:block&quot;]/div[@class=&quot;px-4 lg:mt-4&quot;]/ul[@class=&quot;flex flex-col gap-2.5&quot;]/li[5]/a[@class=&quot;border-b hover:bg-white border-black hover:border-transparent border-b hover:bg-white border-black hover:border-transparent border-b hover:bg-white border-black hover:border-transparent border-b hover:bg-white border-black hover:border-transparent flex font-medium font-poppins text-lg lg:text-xl gap-4 rounded-md py-4 px-2.5&quot;]</value>
      <webElementGuid>d3da7b83-4466-465f-836a-00a1f8cb530d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/section/div/div[2]/ul/li[5]/a</value>
      <webElementGuid>ad295b15-3757-41d8-ba4b-74d3f8855386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Berita')]</value>
      <webElementGuid>6b0bbf90-13cc-45fb-b4d6-7e5e6c18fd1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori'])[1]/following::a[1]</value>
      <webElementGuid>0d927643-d998-4e96-a850-17c62d66ed17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chat Page'])[1]/following::a[2]</value>
      <webElementGuid>9657a14b-b96a-43fa-ab83-5f5c1bec1a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluar'])[1]/preceding::a[1]</value>
      <webElementGuid>04681f76-bd76-49a7-9b11-7187fb4334e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan Diterima'])[1]/preceding::a[1]</value>
      <webElementGuid>ef3fdfe6-fb39-406a-b54f-d9927f87ba7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Berita']/parent::*</value>
      <webElementGuid>8f704aca-9bef-4b17-b1d3-e8883ae3a775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/news')]</value>
      <webElementGuid>aa55634a-96d1-44a3-b7fb-5d3950133478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>b1d743e3-3067-4ca2-b6b5-b72e0b57a06d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/news' and (text() = 'Berita' or . = 'Berita')]</value>
      <webElementGuid>e1895ffb-8f2b-4d7a-8913-38151d419aec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
