<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Terverifikasi</name>
   <tag></tag>
   <elementGuidId>cdd7423f-9e66-463d-99f5-ab7d019e5ab3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/section/div[2]/div/div/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Terverifikasi&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dbe12906-90be-4e25-8449-0c0c0e049ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute top-[105px] left-[7px] font-bold text-[#1a1a1a] text-[20px]</value>
      <webElementGuid>2cfbfa4f-b698-4168-9295-bbf101d69327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Terverifikasi</value>
      <webElementGuid>b5783830-9920-41f1-bfa4-686e4a6f3e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/section[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;lg:ml-72 min-h-[80dvh] overflow-y-auto&quot;]/div[@class=&quot;flex-grow bg-light-2 p-8&quot;]/div[@class=&quot;justify-center w-full flex-wrap flex flex-col lg:flex-row gap-4&quot;]/div[@class=&quot;relative w-full max-w-[250px] h-[141px] bg-warning-3 rounded-[10px] overflow-hidden m-2&quot;]/div[@class=&quot;absolute top-[105px] left-[7px] font-bold text-[#1a1a1a] text-[20px]&quot;]</value>
      <webElementGuid>9c8e763f-797e-465d-9dc6-b3a0f8f39a85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/section/div[2]/div/div/div[2]/div[2]</value>
      <webElementGuid>07b339dd-1e80-49c7-9a7b-14d827ca32e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan Diterima'])[1]/following::div[3]</value>
      <webElementGuid>324a04c7-09cb-4a4e-affb-db7ee74280a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keluar'])[1]/following::div[9]</value>
      <webElementGuid>4757369e-87c3-4663-b0c7-5892b670ce24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sedang Diproses'])[1]/preceding::div[2]</value>
      <webElementGuid>8c95e3f9-e983-45c3-b33f-cb0bbac93b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Laporan Selesai'])[1]/preceding::div[5]</value>
      <webElementGuid>bcbf9e42-e98d-41ad-a6eb-34319972a3e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Terverifikasi']/parent::*</value>
      <webElementGuid>de3105de-26ff-4630-a1a6-1c8d900d32d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]</value>
      <webElementGuid>dfc804b8-2418-4e82-913d-d8baf52e6813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Terverifikasi' or . = 'Terverifikasi')]</value>
      <webElementGuid>39cf42be-966c-41d4-bddb-b5e08f57b408</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
