<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Sa</name>
   <tag></tag>
   <elementGuidId>08419662-f74e-4ee4-b45e-fcd072d359cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/main/section/div[2]/main/section[3]/div[2]/div[2]/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.w-full.mt-5.border.border-gray-300.rounded.p-2.min-h-28</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Sa&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>904fd360-77c9-4986-aa19-b347fa3b7593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full mt-5 border border-gray-300 rounded p-2 min-h-28</value>
      <webElementGuid>21379f38-94c8-4720-8108-24dbc0fa5a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>4a75c916-7cc2-439d-b39b-035027ee6b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sa</value>
      <webElementGuid>66ee7768-6b6b-4f48-977f-911d36480276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/main[1]/section[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;min-h-[80dvh] max-h-max overflow-y-auto bg-light-2&quot;]/main[@class=&quot;lg:ml-80 py-3 pb-10 px-2 lg:pr-7&quot;]/section[@class=&quot;flex flex-col lg:flex-row gap-4 mt-6 w-full&quot;]/div[@class=&quot;bg-white w-full rounded-2xl py-4 px-5 flex flex-col gap-4&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/textarea[@class=&quot;w-full mt-5 border border-gray-300 rounded p-2 min-h-28&quot;]</value>
      <webElementGuid>260895a7-6acf-48f9-8e28-00b75e6fab94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/main/section/div[2]/main/section[3]/div[2]/div[2]/textarea</value>
      <webElementGuid>d23d9e02-3a49-45e7-8ca6-32a49249865c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin Lebak'])[4]/following::textarea[1]</value>
      <webElementGuid>027a0668-bedb-42bc-8eb1-98fcebbab4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim Diskusi'])[1]/preceding::textarea[1]</value>
      <webElementGuid>a6f0ffdb-f5d4-4b70-808c-db8a936954ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sa']/parent::*</value>
      <webElementGuid>268a1610-9992-4235-a918-5ad60190d6f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>28455a21-e597-4391-8c58-1302742eacd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[(text() = 'Sa' or . = 'Sa')]</value>
      <webElementGuid>16fbe933-ac50-4dd6-bcb7-4fd1aa7ca99d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
