<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Sab</name>
   <tag></tag>
   <elementGuidId>04c696c6-0631-4800-bc29-5bb1f8af2d5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/main/section/div[2]/main/section[3]/div[2]/div[2]/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.w-full.mt-5.border.border-gray-300.rounded.p-2.min-h-28</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Sab&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c8d3bfd9-ed5f-4656-bb68-0bc45604024e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full mt-5 border border-gray-300 rounded p-2 min-h-28</value>
      <webElementGuid>4ac6009c-9ec1-4c7d-8b33-59956762594b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>6e56f7ee-4bfa-464e-8889-f775869fd870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sab</value>
      <webElementGuid>1489415b-8656-46a0-bcce-eb0643b2f7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/main[1]/section[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;min-h-[80dvh] max-h-max overflow-y-auto bg-light-2&quot;]/main[@class=&quot;lg:ml-80 py-3 pb-10 px-2 lg:pr-7&quot;]/section[@class=&quot;flex flex-col lg:flex-row gap-4 mt-6 w-full&quot;]/div[@class=&quot;bg-white w-full rounded-2xl py-4 px-5 flex flex-col gap-4&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/textarea[@class=&quot;w-full mt-5 border border-gray-300 rounded p-2 min-h-28&quot;]</value>
      <webElementGuid>52488d8d-4915-409c-be10-d49c35c5571c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/main/section/div[2]/main/section[3]/div[2]/div[2]/textarea</value>
      <webElementGuid>1c1155bf-727d-4305-add5-b1b0d9a2f6dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin Lebak'])[4]/following::textarea[1]</value>
      <webElementGuid>6845d3e7-4c52-4623-9eeb-06bcf04153c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim Diskusi'])[1]/preceding::textarea[1]</value>
      <webElementGuid>6155e2e8-6931-4a16-a4e0-fa400e6f0c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sab']/parent::*</value>
      <webElementGuid>5b2a6cff-6237-40ea-aff7-879e163ae5e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>254a2531-d269-4bd3-89fc-04c5951f3e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[(text() = 'Sab' or . = 'Sab')]</value>
      <webElementGuid>c414deea-31a2-4bce-b0ea-87d12a436caa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
