<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Sabar y</name>
   <tag></tag>
   <elementGuidId>d5c8afd9-1d65-4239-9777-411f45222e93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/main/section/div[2]/main/section[3]/div[2]/div[2]/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.w-full.mt-5.border.border-gray-300.rounded.p-2.min-h-28</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Sabar y&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>0ac004ae-e9a0-486b-9444-f815431681af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full mt-5 border border-gray-300 rounded p-2 min-h-28</value>
      <webElementGuid>d1b3a255-e454-40ce-8d1d-5830f323dc2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>01077a87-a13c-4422-bd2d-607a30725c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sabar y</value>
      <webElementGuid>c4058311-97fe-41aa-a194-6d83600d43b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/main[1]/section[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;min-h-[80dvh] max-h-max overflow-y-auto bg-light-2&quot;]/main[@class=&quot;lg:ml-80 py-3 pb-10 px-2 lg:pr-7&quot;]/section[@class=&quot;flex flex-col lg:flex-row gap-4 mt-6 w-full&quot;]/div[@class=&quot;bg-white w-full rounded-2xl py-4 px-5 flex flex-col gap-4&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/textarea[@class=&quot;w-full mt-5 border border-gray-300 rounded p-2 min-h-28&quot;]</value>
      <webElementGuid>d946954b-bf3a-4062-b1ac-ee65d8af9646</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/main/section/div[2]/main/section[3]/div[2]/div[2]/textarea</value>
      <webElementGuid>08ac5895-3888-4b52-a9c5-0383ea4550ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin Lebak'])[4]/following::textarea[1]</value>
      <webElementGuid>052cf816-a11a-42e2-a25e-1b8aca0a956c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim Diskusi'])[1]/preceding::textarea[1]</value>
      <webElementGuid>3bdf3b70-2a24-4c32-a759-d5d1541de6ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sabar y']/parent::*</value>
      <webElementGuid>a71acb4e-f67d-4dae-a1af-744fc26c4700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>2387897a-a89a-423c-855b-f9abd38350d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[(text() = 'Sabar y' or . = 'Sabar y')]</value>
      <webElementGuid>2105cf57-c9b3-4aad-bc0e-d800c4d5f6d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
