<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Sabar_1</name>
   <tag></tag>
   <elementGuidId>a8f95125-8a04-462c-b082-3170f605a821</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/main/section/div[2]/main/section[3]/div[2]/div[2]/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea.w-full.mt-5.border.border-gray-300.rounded.p-2.min-h-28</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Sabar&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7e23cb13-7d98-494b-95e7-0ba5eeddb4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full mt-5 border border-gray-300 rounded p-2 min-h-28</value>
      <webElementGuid>b081cb93-ba4c-47ad-9c87-da7de34bff3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>300bc5d3-255e-4679-93c3-9f9e3b3cc472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sabar </value>
      <webElementGuid>3fe656ff-b131-423e-b1dd-767520adbf54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/main[1]/section[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;min-h-[80dvh] max-h-max overflow-y-auto bg-light-2&quot;]/main[@class=&quot;lg:ml-80 py-3 pb-10 px-2 lg:pr-7&quot;]/section[@class=&quot;flex flex-col lg:flex-row gap-4 mt-6 w-full&quot;]/div[@class=&quot;bg-white w-full rounded-2xl py-4 px-5 flex flex-col gap-4&quot;]/div[@class=&quot;flex flex-col w-full&quot;]/textarea[@class=&quot;w-full mt-5 border border-gray-300 rounded p-2 min-h-28&quot;]</value>
      <webElementGuid>29f4890d-abc2-4a23-b43f-9a4e77b23997</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/main/section/div[2]/main/section[3]/div[2]/div[2]/textarea</value>
      <webElementGuid>3f578494-7618-4746-afaa-20fdac0b695b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admin Lebak'])[4]/following::textarea[1]</value>
      <webElementGuid>38c0e590-ae27-4c4c-9664-f2ad672ad134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim Diskusi'])[1]/preceding::textarea[1]</value>
      <webElementGuid>99e67a14-64e9-4938-b5bc-1ce08fbef6a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sabar']/parent::*</value>
      <webElementGuid>697d4de9-31ff-4c97-bad0-30db57f32810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f106ed07-79b6-4b7a-a0d4-abe079fdb483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[(text() = 'Sabar ' or . = 'Sabar ')]</value>
      <webElementGuid>7d364bd0-0cc5-40c6-ab7d-1a3f842f194a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
