<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Login</name>
   <tag></tag>
   <elementGuidId>624eb47a-8ad8-423a-8040-b8eeef66c09e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/main/div/div[2]/form/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.text-center.text-zinc-900.text-sm.font-medium.font-poppins</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Login&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>341b0e00-1e35-40a3-90b8-0e8554489cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center text-zinc-900 text-sm font-medium font-poppins</value>
      <webElementGuid>070bc601-24d1-43ca-af06-d6643559665c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>f1a4d31a-96d0-4ecd-8af4-5f3cdd5ed5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/main[1]/div[@class=&quot;h-svh grid place-items-center md:flex md:flex-row py-6 px-6 md:px-0 md:py-0&quot;]/div[@class=&quot;flex flex-col h-auto py-5 px-3 lg:h-full bg-white rounded-md lg:rounded-none w-full lg:w-6/12 lg:justify-center lg:gap-14 lg:px-28&quot;]/form[1]/button[@class=&quot;bg-main-color w-full px-6 mt-5 mb-3 lg:mb-0 lg:mt-8 py-2.5 justify-center items-center inline-flex rounded-md shadow-lg hover:bg-main-darker&quot;]/span[@class=&quot;text-center text-zinc-900 text-sm font-medium font-poppins&quot;]</value>
      <webElementGuid>b0877b2c-b2a7-4eab-9d38-dc4210f7c93d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/main/div/div[2]/form/button/span</value>
      <webElementGuid>86f4e6dc-0f55-421c-abcf-e1e9407fc03c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[3]/following::span[1]</value>
      <webElementGuid>839a04bf-bef6-4d8e-baea-742e2b7f42db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[2]/following::span[3]</value>
      <webElementGuid>9d869c8d-95b9-41a2-887a-8bb01d39ec5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>65c934af-34ba-400e-8edb-b17470775ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button/span</value>
      <webElementGuid>8d506c1a-acc7-4988-8a49-e6c32c14ee4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>8ec36f6b-bca1-4991-ac2b-7000af3f3bb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
