<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Detail</name>
   <tag></tag>
   <elementGuidId>a525ac59-cc82-4249-8c58-a5887fb71343</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/section/div[2]/div/div[2]/div[2]/div/div/div[2]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Detail&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6f50688c-e7b8-4eca-ae36-5af362724c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-info-3 text-white px-6 py-2.5 rounded shadow</value>
      <webElementGuid>ac9751bb-c15f-4608-881b-f964c44ab1fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>99091b90-6759-477a-8ff2-f66b3165744c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/section[@class=&quot;flex w-full flex-col&quot;]/div[@class=&quot;flex-grow lg:ml-[287px] min-h-[80dvh] overflow-y-auto&quot;]/div[@class=&quot;bg-light-2 px-8&quot;]/div[@class=&quot;container mt-9 w-full bg-gray-300 justify-between px-5 pt-5 rounded-lg min-h-[70vh]&quot;]/div[@class=&quot;container w-full flex flex-wrap gap-2&quot;]/div[1]/div[@class=&quot;lg:w-[486px] h-auto px-5 py-8 bg-slate-50 rounded-2xl flex flex-col shadow&quot;]/div[@class=&quot;flex gap-6 mt-auto items-center justify-between&quot;]/div[@class=&quot;flex gap-6&quot;]/button[@class=&quot;bg-info-3 text-white px-6 py-2.5 rounded shadow&quot;]</value>
      <webElementGuid>331884b3-0c4c-4de5-aada-9588104bce20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/section/div[2]/div/div[2]/div[2]/div/div/div[2]/div/button</value>
      <webElementGuid>b6f5a449-7758-42d4-b337-c075fdb20bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='furniture gratis nih.'])[1]/following::button[1]</value>
      <webElementGuid>96762518-855a-4a1a-a9a9-1ed4caa5f738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='furniture baru'])[1]/following::button[1]</value>
      <webElementGuid>3ff16424-2c33-492d-a90d-5cf3335abebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[1]/preceding::button[1]</value>
      <webElementGuid>255611b4-4efa-477d-b3a4-4e4304a120ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Perbaikan Fasilitas Kesehatan di RSUD Tangerang Tanggapi Kritik Masyarakat'])[1]/preceding::button[2]</value>
      <webElementGuid>805d2b53-b48d-4b07-b420-4550b6b19897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Detail']/parent::*</value>
      <webElementGuid>f444058f-0f50-4a75-8daa-c028125f7b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/button</value>
      <webElementGuid>567a83f1-c0ad-4719-b276-63bbacda2f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Detail' or . = 'Detail')]</value>
      <webElementGuid>775db426-a9e8-46d1-b2df-78c904c5abb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
